#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 检查是否有依赖文件的更改
if git diff HEAD@{1} --name-only | grep -q "^package-lock.json\|^yarn.lock\|^pnpm-lock.yaml"; then
  echo "📦 检测到依赖文件有更新，正在安装新的依赖..."
  pnpm install
fi

# 检查是否有配置文件的更改
if git diff HEAD@{1} --name-only | grep -q "^.env\|^.env.*\|^config/"; then
  echo "⚙️ 检测到配置文件有更新，请检查是否需要更新本地配置"
fi
